version: '3.1'
services:
  stats-server:
    image: stats-service
    build: ewm-stats-service/server
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/java-explore-stats
      - POSTGRES_DB=java-explore-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"

    volumes:
      - /var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=java-explore-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    image: main-service
    build: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/java-explore-main
      - POSTGRES_DB=java-explore-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"

    volumes:
      - /var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=java-explore-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
